#!/bin/bash
#SBATCH --job-name=map    # Job name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=u247529@bcm.edu     # Where to send mail
#SBATCH --ntasks=8                    # Run on a single CPU
#SBATCH --mem=100gb                     # Job memory request
#SBATCH --time=24:00:00               # Time limit hrs:min:sec
#SBATCH --output=serial_test_%j.log   # Standard output and error log
module load bwa
module load samtools

#USE BWA TO MAP FASTQ FILES TO REFERENCE GENOME
for file in fastq/*.fastq.gz
do
output=${file/_S[0-9][0-9][0-9][0-9]_L00[0-9]_R1_001.fastq.gz/.sam}
bam=${output/sam/bam}
bwa mem -t 8 Homo_sapiens_assembly38.fasta $file > $output
samtools view -Sb -o $bam $output
done


