#!/bin/bash
#SBATCH --fastqc    # Job name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=u247529@bcm.edu     # Where to send mail    
#SBATCH --ntasks=1                    # Run on a single CPU
#SBATCH --mem=60gb                     # Job memory request
#SBATCH --time=03:00:00               # Time limit hrs:min:sec
#SBATCH --output=serial_test_%j.log   # Standard output and error log


#USE FASTQC TO CHECK THE QUALITY OF FASTQ FILES AND FILTER (USE TO FILTER LOW QUALITY)

module load fastqc
fastqc -o fastqc_out *.fastq.gz

#COMBINE FASTQC RESULTS INTO ONE (INSTALL WITH PIP)

multiqc fastqc_out/
