#!/bin/bash
#SBATCH --job-name=funcotator    # Job name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=u247529@bcm.edu     # Where to send mail
#SBATCH --ntasks=32                    # Run on a single CPU
#SBATCH --mem=100gb                     # Job memory request
#SBATCH --time=98:00:00               # Time limit hrs:min:sec
#SBATCH --output=serial_test_%j.log   # Standard output and error log
module load java
module load gatk
for file in mutect_filtered/*.vcf
do
output=${file/_mutect_filtered.vcf/_funcotated.vcf}
gatk Funcotator --variant $file \
 --reference Homo_sapiens_assembly38.fasta \
 --ref-version hg38 \
 --data-sources-path funcotator_dataSources.v1.7.20200521s \
 --output $output \
 --output-file-format VCF
done
